CREATE DATABASE diem;
USE diemthi;

CREATE TABLE hocsinh(
maHS VARCHAR (50) PRIMARY KEY,
ngaysinh DATETIME,
lop VARCHAR(20),
GT VARCHAR(10)
);


CREATE TABLE GV(
MaGV VARCHAR(50) PRIMARY KEY,
TenGV VARCHAR(50),
SDT VARCHAR(20)
);

CREATE TABLE MONHOC(
MaMH VARCHAR(50) PRIMARY KEY,
TenMH VARCHAR(20),
MaGV VARCHAR(50),
FOREIGN KEY (MaGV)  REFERENCES GV(MaGV)
);